name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Checkout KernelPatch
        uses: actions/checkout@v4
        with:
          repository: bmax121/KernelPatch
          ref: 0.13.1
          path: KernelPatch

      - name: Build
        run: make ANDROID_NDK=$ANDROID_NDK_LATEST_HOME KP_DIR=KernelPatch MYKPM_VERSION=$(git describe --tags | sed 's/v//')
      
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: splfix_*.kpm
          generate_release_notes: true
